#!/usr/bin/env bash
# Shared helpers for the dspy-jev setup scripts. Sourced, not executed.

set -euo pipefail

DSPY_JEV_ROOT="${DSPY_JEV_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
VENV_DIR="${DSPY_JEV_VENV:-$DSPY_JEV_ROOT/.venv}"

if [[ -t 1 ]]; then
  C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_ERR=$'\033[31m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
  C_OK=""; C_WARN=""; C_ERR=""; C_DIM=""; C_OFF=""
fi

step() { printf '%s==>%s %s\n' "$C_DIM" "$C_OFF" "$*"; }
ok()   { printf '%s  ok%s  %s\n' "$C_OK" "$C_OFF" "$*"; }
warn() { printf '%swarn%s  %s\n' "$C_WARN" "$C_OFF" "$*" >&2; }
die()  { printf '%sfail%s  %s\n' "$C_ERR" "$C_OFF" "$*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

require_python() {
  local python_bin
  python_bin="$(command -v python3 || true)"
  [[ -n "$python_bin" ]] || die "python3 not found. Install Python 3.10 or newer."
  "$python_bin" - <<'PY' || die "dspy-jev needs Python 3.10 or newer."
import sys
raise SystemExit(0 if (3, 10) <= sys.version_info < (3, 14) else 1)
PY
  echo "$python_bin"
}

create_venv() {
  local python_bin="$1"
  if [[ -d "$VENV_DIR" ]]; then
    ok "virtual environment already at $VENV_DIR"
    return
  fi
  step "creating virtual environment at $VENV_DIR"
  if have uv; then
    uv venv "$VENV_DIR" --python "$python_bin"
  else
    "$python_bin" -m venv "$VENV_DIR"
  fi
  ok "virtual environment created"
}

pip_install() {
  # shellcheck disable=SC1091
  source "$VENV_DIR/bin/activate"
  if have uv; then
    uv pip install --python "$VENV_DIR/bin/python" "$@"
  else
    "$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
    "$VENV_DIR/bin/python" -m pip install "$@"
  fi
}

install_project() {
  local extras="${1:-service,observability,mcp}"
  step "installing dspy-jev[$extras]"
  # Braces are required: `$VAR[...]` reads as an array subscript.
  pip_install -e "${DSPY_JEV_ROOT}[${extras}]"
  ok "installed"
}

write_env_file() {
  # write_env_file <harness> <key=value>...
  local harness="$1"; shift
  local env_file="$DSPY_JEV_ROOT/.env"
  if [[ -f "$env_file" ]]; then
    warn "$env_file already exists; leaving it alone"
    return
  fi
  step "writing $env_file"
  {
    echo "# Generated by scripts/setup_${harness}.sh"
    echo "DSPY_JEV_HARNESS=$harness"
    for pair in "$@"; do echo "$pair"; done
  } > "$env_file"
  chmod 600 "$env_file"
  ok "wrote $env_file (mode 600)"
}

require_key() {
  # require_key <VAR_NAME> <where to get one>
  local name="$1" hint="$2"
  if [[ -z "${!name:-}" ]]; then
    warn "$name is not set. $hint"
    warn "Export it, or add it to $DSPY_JEV_ROOT/.env, before running 'dspy-jev doctor'."
    return 1
  fi
  ok "$name is set"
}

run_doctor() {
  step "running dspy-jev doctor"
  "$VENV_DIR/bin/dspy-jev" doctor "$@" || warn "doctor reported failures; see the output above"
}
